# HER2+ Breast Cancer Gene Expression Analysis

## 1. Data Exploration
This notebook explores the structure of the GSE245132 gene expression dataset before performing downstream analysis.

### Goals
- Load the processed GEO series matrix
- Inspect the dimensions and structure of the expression data
- Identify sample and feature information
- Prepare the data for baseline vs. post-treatment comparison

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

os.getcwd()

'/home/sis02/Projects/her2-gene-expression-analysis/notebooks'

In [3]:
data_path = "../data/GSE245132_series_matrix.txt"
os.path.exists(data_path)

True

In [4]:
expression_df = pd.read_csv(
    data_path,
    sep="\t",
    skiprows=62
) 
# expression_df는 expression matrix를 저장한 DataFrame variable
# \t는 tab 즉: 각 column은 tab으로 구분되어 있다고 pandas에게 알려주는 것
# skiprows=62는 앞의 62줄을 건너뛰고 읽어라 -> 63번째 줄인 "ID_REF" "FSM7837244" ...를 column names/header로 사용하게 됨
expression_df.head()
# DataFrame의 처음 5개 rows를 보여줌

,ID_REF,GSM7837244,GSM7837245,GSM7837246,GSM7837247,GSM7837248,GSM7837249,GSM7837250,GSM7837251,GSM7837252,...,GSM7837298,GSM7837299,GSM7837300,GSM7837301,GSM7837302,GSM7837303,GSM7837304,GSM7837305,GSM7837306,GSM7837307
0,TC0100006437.hg.1,6.699491,7.023459,6.866237,6.864067,7.116156,7.154243,6.738917,6.983281,6.911802,...,7.019715,6.748944,6.868323,6.681636,6.707026,7.081187,7.180591,6.795221,6.935736,7.270319
1,TC0100006476.hg.1,5.858871,5.511078,5.757049,5.653263,5.634929,5.586172,5.651388,5.587537,5.569932,...,5.755594,5.715699,5.748914,5.759298,5.846549,5.508467,5.604463,5.795497,5.686680,5.724931
2,TC0100006479.hg.1,7.527140,7.591499,7.641178,7.312896,7.472248,7.511117,7.228207,7.559089,7.417284,...,7.666647,7.549583,7.720754,7.357933,7.510737,7.525719,7.719205,7.725928,7.518623,7.442325
3,TC0100006480.hg.1,6.642914,6.886240,6.772836,6.589355,6.950437,6.965211,6.681968,6.844155,6.572749,...,6.828575,7.108570,6.777758,6.651523,6.652452,7.013474,6.946153,6.860686,6.952366,7.149339
4,TC0100006483.hg.1,12.362670,10.831000,11.652310,11.119240,11.445440,11.684410,11.631090,11.263410,11.904260,...,11.710190,11.200480,11.331710,11.079830,12.120670,10.616840,11.950550,11.417210,11.524020,11.375900

In [5]:
expression_df.shape

(21449, 65)

In [6]:
expression_df.tail()

,ID_REF,GSM7837244,GSM7837245,GSM7837246,GSM7837247,GSM7837248,GSM7837249,GSM7837250,GSM7837251,GSM7837252,...,GSM7837298,GSM7837299,GSM7837300,GSM7837301,GSM7837302,GSM7837303,GSM7837304,GSM7837305,GSM7837306,GSM7837307
21444,TSUnmapped00000820.hg.1,7.215323,6.908916,7.527110,7.148620,7.716397,7.086964,7.247353,7.044221,6.819007,...,7.368483,6.892673,7.249774,7.222658,6.754844,7.397474,6.929242,7.388697,7.324537,7.414706
21445,TSUnmapped00000821.hg.1,5.682681,5.562259,5.734435,5.939415,5.677493,5.947857,5.632574,5.588262,5.652801,...,5.742899,5.617142,5.525916,5.623251,5.640113,5.852871,5.923877,5.963168,5.694182,5.609817
21446,TSUnmapped00000822.hg.1,5.247820,5.763969,5.540705,5.572333,5.419194,5.488442,5.624328,5.646287,5.568121,...,5.573056,5.858377,5.683992,5.503022,5.345350,5.598806,5.633884,5.699905,5.382211,5.430044
21447,TSUnmapped00000823.hg.1,7.893728,7.931292,7.922690,7.960620,8.033476,8.011501,7.836545,8.060505,7.856040,...,7.889155,7.714014,7.941951,7.626719,7.628978,7.830407,8.103840,8.040696,7.881028,7.690736
21448,!series_matrix_table_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
expression_df["ID_REF"] != "!series_matrix_table_end"

0         True
1         True
2         True
3         True
4         True
         ...
21444     True
21445     True
21446     True
21447     True
21448    False
Name: ID_REF, Length: 21449, dtype: bool

In [8]:
expression_df[
    expression_df["ID_REF"] != "!series_matrix_table_end"
]

,ID_REF,GSM7837244,GSM7837245,GSM7837246,GSM7837247,GSM7837248,GSM7837249,GSM7837250,GSM7837251,GSM7837252,...,GSM7837298,GSM7837299,GSM7837300,GSM7837301,GSM7837302,GSM7837303,GSM7837304,GSM7837305,GSM7837306,GSM7837307
0,TC0100006437.hg.1,6.699491,7.023459,6.866237,6.864067,7.116156,7.154243,6.738917,6.983281,6.911802,...,7.019715,6.748944,6.868323,6.681636,6.707026,7.081187,7.180591,6.795221,6.935736,7.270319
1,TC0100006476.hg.1,5.858871,5.511078,5.757049,5.653263,5.634929,5.586172,5.651388,5.587537,5.569932,...,5.755594,5.715699,5.748914,5.759298,5.846549,5.508467,5.604463,5.795497,5.686680,5.724931
2,TC0100006479.hg.1,7.527140,7.591499,7.641178,7.312896,7.472248,7.511117,7.228207,7.559089,7.417284,...,7.666647,7.549583,7.720754,7.357933,7.510737,7.525719,7.719205,7.725928,7.518623,7.442325
3,TC0100006480.hg.1,6.642914,6.886240,6.772836,6.589355,6.950437,6.965211,6.681968,6.844155,6.572749,...,6.828575,7.108570,6.777758,6.651523,6.652452,7.013474,6.946153,6.860686,6.952366,7.149339
4,TC0100006483.hg.1,12.362670,10.831000,11.652310,11.119240,11.445440,11.684410,11.631090,11.263410,11.904260,...,11.710190,11.200480,11.331710,11.079830,12.120670,10.616840,11.950550,11.417210,11.524020,11.375900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21443,TSUnmapped00000819.hg.1,7.360468,7.105131,7.261381,7.076610,6.810274,6.848968,7.222497,7.087993,7.179842,...,6.961360,7.164807,7.087227,7.152398,7.335340,6.904150,6.959280,6.839369,7.192832,7.203874
21444,TSUnmapped00000820.hg.1,7.215323,6.908916,7.527110,7.148620,7.716397,7.086964,7.247353,7.044221,6.819007,...,7.368483,6.892673,7.249774,7.222658,6.754844,7.397474,6.929242,7.388697,7.324537,7.414706
21445,TSUnmapped00000821.hg.1,5.682681,5.562259,5.734435,5.939415,5.677493,5.947857,5.632574,5.588262,5.652801,...,5.742899,5.617142,5.525916,5.623251,5.640113,5.852871,5.923877,5.963168,5.694182,5.609817
21446,TSUnmapped00000822.hg.1,5.247820,5.763969,5.540705,5.572333,5.419194,5.488442,5.624328,5.646287,5.568121,...,5.573056,5.858377,5.683992,5.503022,5.345350,5.598806,5.633884,5.699905,5.382211,5.430044
21447,TSUnmapped00000823.hg.1,7.893728,7.931292,7.922690,7.960620,8.033476,8.011501,7.836545,8.060505,7.856040,...,7.889155,7.714014,7.941951,7.626719,7.628978,7.830407,8.103840,8.040696,7.881028,7.690736

In [9]:
expression_clean_df = expression_df[
    expression_df["ID_REF"] != "!series_matrix_table_end"
].copy()

In [10]:
expression_df.shape

(21449, 65)

In [11]:
expression_clean_df.shape

(21448, 65)

In [12]:
expression_clean_df.columns

Index(['ID_REF', 'GSM7837244', 'GSM7837245', 'GSM7837246', 'GSM7837247',
       'GSM7837248', 'GSM7837249', 'GSM7837250', 'GSM7837251', 'GSM7837252',
       'GSM7837253', 'GSM7837254', 'GSM7837255', 'GSM7837256', 'GSM7837257',
       'GSM7837258', 'GSM7837259', 'GSM7837260', 'GSM7837261', 'GSM7837262',
       'GSM7837263', 'GSM7837264', 'GSM7837265', 'GSM7837266', 'GSM7837267',
       'GSM7837268', 'GSM7837269', 'GSM7837270', 'GSM7837271', 'GSM7837272',
       'GSM7837273', 'GSM7837274', 'GSM7837275', 'GSM7837276', 'GSM7837277',
       'GSM7837278', 'GSM7837279', 'GSM7837280', 'GSM7837281', 'GSM7837282',
       'GSM7837283', 'GSM7837284', 'GSM7837285', 'GSM7837286', 'GSM7837287',
       'GSM7837288', 'GSM7837289', 'GSM7837290', 'GSM7837291', 'GSM7837292',
       'GSM7837293', 'GSM7837294', 'GSM7837295', 'GSM7837296', 'GSM7837297',
       'GSM7837298', 'GSM7837299', 'GSM7837300', 'GSM7837301', 'GSM7837302',
       'GSM7837303', 'GSM7837304', 'GSM7837305', 'GSM7837306', 'GSM7837307'],
      dtype='str')

In [13]:
sample_columns = expression_clean_df.columns[1:]

In [14]:
len(sample_columns)

64

In [15]:
!grep '!Sample_title' ../data/GSE245132_series_matrix.txt

!Sample_title	"Pt16_Baseline"	"Pt14_Baseline"	"Pt18_Baseline"	"Pt19_Post"	"Pt20_Post"	"Pt29_Post"	"Pt29_Baseline"	"Pt30_Baseline"	"Pt15_Baseline"	"Pt19_Baseline"	"Pt20_Baseline"	"Pt30_Post"	"Pt15_Post"	"Pt17_Baseline"	"Pt17_Post"	"Pt18_Post"	"Pt16_Post"	"Pt14_Post"	"Pt13_Baseline"	"Pt13_Post"	"Pt12_Baseline"	"Pt12_Post"	"Pt11_Baseline"	"Pt11_Post"	"Pt31_Baseline"	"Pt31_Post"	"Pt32_Baseline"	"Pt6_Baseline"	"Pt7_Baseline"	"Pt7_Post"	"Pt32_Post"	"Pt8_Baseline"	"Pt10_Baseline"	"Pt8_Post"	"Pt10_Post"	"Pt9_Post"	"Pt6_Post"	"Pt9_Baseline"	"Pt1_Baseline"	"Pt4_Post"	"Pt1_Post"	"Pt5_Baseline"	"Pt5_Post"	"Pt4_Baseline"	"Pt3_Post"	"Pt3_Baseline"	"Pt24_Baseline"	"Pt24_Post"	"Pt27_Baseline"	"Pt21_Post"	"Pt23_Post"	"Pt2_Baseline"	"Pt25_Post"	"Pt22_Post"	"Pt23_Baseline"	"Pt27_Post"	"Pt22_Baseline"	"Pt28_Post"	"Pt26_Baseline"	"Pt26_Post"	"Pt28_Baseline"	"Pt2_Post"	"Pt21_Baseline"	"Pt25_Baseline"

In [16]:
sample_title_line = None

with open(data_path, "r", encoding="utf-8") as file:
    for line in file:
        if line.startswith("!Sample_title"):
            sample_title_line = line
            break

In [17]:
sample_title_line[:200]

'!Sample_title\t"Pt16_Baseline"\t"Pt14_Baseline"\t"Pt18_Baseline"\t"Pt19_Post"\t"Pt20_Post"\t"Pt29_Post"\t"Pt29_Baseline"\t"Pt30_Baseline"\t"Pt15_Baseline"\t"Pt19_Baseline"\t"Pt20_Baseline"\t"Pt30_Post"\t"Pt15_Post'

In [18]:
sample_titles = sample_title_line.split("\t")[1:]

In [19]:
len(sample_titles)

64

In [20]:
sample_titles[:5]

['"Pt16_Baseline"',
 '"Pt14_Baseline"',
 '"Pt18_Baseline"',
 '"Pt19_Post"',
 '"Pt20_Post"']

In [21]:
clean_titles = []

for title in sample_titles:
    clean_titles.append(title.strip().strip('"'))

In [22]:
clean_titles[:5]

['Pt16_Baseline', 'Pt14_Baseline', 'Pt18_Baseline', 'Pt19_Post', 'Pt20_Post']

In [23]:
metadata_df = pd.DataFrame({
    "sample_id": sample_columns,
    "sample_title": clean_titles
})

In [24]:
metadata_df.head()

    sample_id   sample_title
0  GSM7837244  Pt16_Baseline
1  GSM7837245  Pt14_Baseline
2  GSM7837246  Pt18_Baseline
3  GSM7837247      Pt19_Post
4  GSM7837248      Pt20_Post

In [25]:
clean_titles[0].split("_")

['Pt16', 'Baseline']

In [26]:
patients =[]
timepoints = []

for title in clean_titles:
    parts = title.split("_")
    patients.append(parts[0])
    timepoints.append(parts[1])

In [27]:
patients[:5]

['Pt16', 'Pt14', 'Pt18', 'Pt19', 'Pt20']

In [28]:
timepoints[:5]

['Baseline', 'Baseline', 'Baseline', 'Post', 'Post']

In [29]:
metadata_df["patient"] = patients
metadata_df["timepoint"] = timepoints

In [30]:
metadata_df.head()

    sample_id   sample_title patient timepoint
0  GSM7837244  Pt16_Baseline    Pt16  Baseline
1  GSM7837245  Pt14_Baseline    Pt14  Baseline
2  GSM7837246  Pt18_Baseline    Pt18  Baseline
3  GSM7837247      Pt19_Post    Pt19      Post
4  GSM7837248      Pt20_Post    Pt20      Post

In [31]:
baseline_samples = metadata_df[
    metadata_df["timepoint"] == "Baseline"
].copy()

In [32]:
post_samples = metadata_df[
    metadata_df["timepoint"] == "Post"
].copy()

In [33]:
baseline_samples.shape

(32, 4)

In [34]:
post_samples.shape

(32, 4)

In [35]:
metadata_df["timepoint"].unique()

<StringArray>
['Baseline', 'Post']
Length: 2, dtype: str

### Data Cleaning and Metadata Summary

- Loaded the GEO series matrix into a Pandas DataFrame.
- Removed the `!series_matrix_table_end` row using Boolean filtering.
- The cleaned expression matrix contains 21,448 expression features and 64 samples.
- Extracted 64 GSM sample IDs from the expression matrix columns.
- Extracted and cleaned sample titles from the GEO metadata.
- Created a metadata DataFrame containing sample ID, sample title, patient ID, and timepoint.
- Confirmed 32 Baseline and 32 Post-treatment samples.

During data cleaning, one Baseline sample initially contained an extra newline character (`\n`). This was identified using `.unique()` and corrected using string cleaning.

In [36]:
baseline_samples.shape

(32, 4)

In [37]:
post_samples.shape

(32, 4)

In [38]:
metadata_df["timepoint"].unique()

<StringArray>
['Baseline', 'Post']
Length: 2, dtype: str